### ISSUE TITLE
File exists strategy

### ISSUE THREAD

**Issue by mmaelicke** [Deadwood-ai/file-storage-api#2]
There is a TODO in the code:

https://github.com/Deadwood-ai/file-storage-api/blob/aebffb62570f421b68ad2085366d5f876bd0ae28/storage/app.py#L63

This affects the case, when the user uploads a file, which is already present on the file storage server. Right now, the file names on the users file system are preserved and saved using the same name on the storage server.

I think these kinds of conflicts can arise, ie. when drones, or drone-software, follow some common pattern to name the file, we might end up with a `my-drone-image-1.tif`, `my-drone-image-2.tif` per user or even per flight.

There are different options here:

1. Each user uploads into his/her own folder, so name conflicts are per-user and can be handled with `overwrite` or `exception`.
2. We assign each file a new (random) filename and the upload filename is preserved as metadata (upload name?)
3. We assign each file a new (random) filename and do not care for the original file (weird).
4. We prefix each upload with a date string.

**Comment by JesJehle** [comment]
I would propose a filename combination of name + uuid to identify the image on the file server and store the name, and the hash of the image together with all other metadata in the database.
This way 
* there is no possible error because of identical names
* We don't need individual folders, which complicate the structure
* We still have the name for simple manual check (uuids are not intuitive)
* to identify duplicates during the upload process, we could check the hash

What do you think?

**Comment by mmaelicke** [comment]
Even better. UUIDs are also great to ensure computational provenance for later workflows.
